[aurbuild] Add auto-updating of package database

diff --git a/aurbuild/aurbuild b/aurbuild/aurbuild
--- a/aurbuild/aurbuild
+++ b/aurbuild/aurbuild
@@ -1,5 +1,34 @@
 #!/usr/bin/env bash
 
+shopt -s nullglob
+
+# Utility functions {{{
+  # Logging {{{
+    ansi_reset="$(tput sgr0 || true)"
+    ansi_red="$(tput setaf 1 || true)"
+    ansi_yellow="$(tput setaf 3 || true)"
+    ansi_blue="$(tput setaf 4 || true)"
+    ansi_green="$(tput setaf 2 || true)"
+    log_info()    { echo >&2 "${ansi_blue}[info]${ansi_reset}" "$@"; }
+    log_warn()    { echo >&2 "${ansi_yellow}[warn]${ansi_reset}" "$@"; }
+    log_error()   { echo >&2 "${ansi_red}[ERROR]${ansi_reset}" "$@"; }
+    log_success() { echo >&2 "${ansi_green}[success]${ansi_reset}" "$@"; }
+
+    # Use the log_error function to indicate where an error occurs
+    trap 'log_error line $LINENO' ERR
+  # }}}
+
+    # Checks for command on path
+    command_exists() { whence -- "$@" &> /dev/null; }
+# }}}
+
+# Preliminary checks {{{
+    if command_exists repo-add; then
+        log_error "Package 'aurutils' is not installed!"
+        exit 1
+    fi
+# }}}
+
 if [ -f ~/.aurbuild ]; then
     source ~/.aurbuild
 else
@@ -12,12 +41,20 @@ repository_location=/foo/\$repository_name/\$(uname -m)/
 fi
 
 location="$(pwd)"
+repository_location="${repository_location%?}"
 
 function released_version {
     name=$1
 
     pacman -Ss $name | grep -e "^$repository_name/$name " | cut -d" " -f2
 }
+
+if ! [ -f "$repository_location/$repository_name.db.tar.gz" ]; then
+    echo "repo db not found, creating..."
+    cd "$repository_location"
+    repo-add "$repository_name.db.tar.gz"
+fi
+
 
 packages=()
 echo "initializing build queue"
@@ -53,6 +90,13 @@ for package in ${packages[@]}; do
         failures+=($package)
     fi
 done
+
+if [ -n "$auto_update" ]; then
+    cd "$repository_location"
+    for pkg in "$repository_location"/*.pkg.tar.zst; do
+        repo-add -n "$repository_name.db.tar.gz" "$pkg"
+    done
+fi
 
 cd "$location"
 
